// flow-typed signature: 263ee36cbab6a900f83c91841208dab4
// flow-typed version: <<STUB>>/eslint-plugin-killua_v^1.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-killua'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-killua' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-killua/base' {
  declare module.exports: any;
}

declare module 'eslint-plugin-killua/config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-killua/plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-killua/base.js' {
  declare module.exports: $Exports<'eslint-plugin-killua/base'>;
}
declare module 'eslint-plugin-killua/config.js' {
  declare module.exports: $Exports<'eslint-plugin-killua/config'>;
}
declare module 'eslint-plugin-killua/index' {
  declare module.exports: $Exports<'eslint-plugin-killua'>;
}
declare module 'eslint-plugin-killua/index.js' {
  declare module.exports: $Exports<'eslint-plugin-killua'>;
}
declare module 'eslint-plugin-killua/plugins.js' {
  declare module.exports: $Exports<'eslint-plugin-killua/plugins'>;
}
